#%RAML 1.0 Trait
### to be included in the traits section as fileUpdate

usage: used for a PATCH over a file resource
description: |
  partially updates a file given the file body
body: file
responses:
  200:
    headers:
      x-entity-id: string
      location: string
    body: file
  400:
    body: <<error>>
  401:
    body: <<error>>
  403:
    body: <<error>>
  404:
    body: <<error>>
  405:
    body: <<error>>
  500:
    body: <<error>>