#%RAML 1.0 Trait
### to be included in the traits section as entityRetrieve

usage: used for a GET over an entity resource
description: |
  gets a <<entityType>> entity
responses:
  200:
    headers:
      x-entity-id: string
      x-entity-type: string
      location: string
      Cache-Control: string
      op-monitoring-url: string
    body: <<entityType>>
  400:
    body: <<error>>
  401:
    body: <<error>>
  403:
    body: <<error>>
  404:
    body: <<error>>
  405:
    body: <<error>>
  500:
    body: <<error>>