#%RAML 1.0 ResourceType

description: task service entry point with <<task-name>>, <<task-params>>
usage: on an entry point that implements a task service entry point

displayName: <<task-name>> entity
uriParameters:
  task-id: string
get:
  is: [ entityRetrieve: { entityType: Task, error: Error } ]