#####
# defines an entity resource
#
# Usage : to be included in the resourceTypes section

  uriParameters:
    entity-id: string
  get:
    description: |
      gets a <<entityType>> entity
    responses:
      200:
        headers:
          x-entity-id: string
          location: string
        body: <<entityType>>
      400:
        body: Error
      401:
        body: Error
      403:
        body: Error
      404:
        body: Error
      500:
        body: Error

  put:
    description: |
      replaces a <<entityType>> entity given the <<entityReplaceType>> body
    body: <<entityReplaceType>>
    responses:
      200:
        headers:
          x-entity-id: string
          location: string
        body: <<entityType>>
      400:
        body: Error
      401:
        body: Error
      403:
        body: Error
      404:
        body: Error
      405:
        body: Error
      500:
        body: Error
  patch:
    description: |
      partially updates a <<entityType>> entity given the <<entityUpdateType>> body
    body: <<entityUpdateType>>
    responses:
      200:
        headers:
          x-entity-id: string
          location: string
        body: <<entityType>>
      400:
        body: Error
      401:
        body: Error
      403:
        body: Error
      404:
        body: Error
      405:
        body: Error
      500:
        body: Error
  delete:
    description: deletes an entity
    responses:
      204:
        description: resource deleted
      400:
        body: Error
      401:
        body: Error
      403:
        body: Error
      404:
        body: Error
      500:
        body: Error