#####
# defines the base annotations for codingmatters
#
# Usage : to be included in the annotationTypes section

  value-object-hint:
    type: string[]
  conforms-to:
    type: string[]
  builder-conforms-to:
    type: string[]
  builder-conforms-to-parametrized:
    type: string[]
  already-defined:
    type: string
  already-defined-enum:
    type: string
  object-impl:
    enum: [ Val, ObjectValue ]
  paged-collection:
    type: nil
    allowedTargets: [ Resource ]
  paged-collection-entity:
    type: nil
    allowedTargets: [ Resource ]
  paged-collection-batch:
    type: nil
    allowedTargets: [ Resource ]
  entity-ui:
    type: nil
    allowedTargets: [ Resource ]

  clear-guards:
    type: nil
    allowedTargets: [ Resource, Method ]
    description: |
      stop the guard inheritance

  guard:
    type: string[]
    allowedTargets: [ Resource, Method ]
    description: |
      Examples :
      (guard):
        - permission::FLEXAPPS|api://flexapp/{uri:parameter1}|READ_FLEXAPP
        - permission::{uri:parameter1}|RESOURCE|api://flexapp/{uri:parameter2}|READ_RECORD
        - permission::flexapps|api://flexapp/{uri:parameter1}|read_flexapp
        - permission::{uri:parameter1}|resource|api://flexapp/{uri:parameter2}|read_record
      
      
      When used on flexio apis
      
      permissions: 
        permission::<target-type>|<target>|<permission>
        permission::<flexapp>|<target-type>|<target>|<permission>
      
        <flexapp> is a flexapp id (optional)
        <target-type> values must match io.flexio.permissions.TargetType enum values
        <target> a target url 
        <permission> values must match io.flexio.permissions.Permissions enum value
      
        <target-type> and <permission> values match the enum name, or the lower cased name, or the lower cased names with _ replaced by -.
        All token are trimmed so one can add spaces around the values
        
        <flexapp> and <resource> are templates that can use uri parameters, query parameters and headers with the following syntax :
        {uri:parameter1}{header:parameter2}{query:parameter3}
      
      
      account:
        account::valid|<account name>
        account::valid-connected|<account name>
