#####
# defines the base annotations for codingmatters
#
# Usage : to be included in the annotationTypes section

  value-object-hint:
    type: string[]
  conforms-to:
    type: string[]
  already-defined:
    type: string
  object-impl:
    enum: [ Val, ObjectValue ]
  paged-collection:
    type: nil
    allowedTargets: [ Resource ]
  paged-collection-entity:
    type: nil
    allowedTargets: [ Resource ]
  entity-ui:
    type: nil
    allowedTargets: [ Resource ]