#%RAML 1.0 DataType
# defines error type with templated messages
#
# Usage : to be included in the types section as Message: !include ...

type: object
properties:
  success:
    type: array
    items: string
  errors:
    type: array
    items:
      type: object
      properties:
        entity: object
        error: Error