#%RAML 1.0 DataType
# defines metadata for a common entity
#
# Usage : to be included in the types section as EntityMetadata: !include ...

type: object
properties:
  created-at: datetime-only
  created-by: string
  updated-at: datetime-only
  updated-by: string