#%RAML 1.0 DataType
# defines error type with templated messages
#
# Usage : to be included in the types section as Error: !include ...

type: object
properties:
  token: string
  code:
    enum: [
      ILLEGAL_RANGE_SPEC,
      ILLEGAL_FILTER_SPEC,
      UNEXPECTED_ERROR,
      OVERLOADED,
      RESOURCE_NOT_FOUND,
      ILLEGAL_RESOURCE_CREATION,
      ILLEGAL_RESOURCE_CHANGE,
      INVALID_OBJECT_FOR_CREATION,
      INVALID_OBJECT_FOR_REPLACEMENT,
      INVALID_OBJECT_FOR_UPDATE,
      ENTITY_RETRIEVE_NOT_ALLOWED,
      ENTITY_CREATION_NOT_ALLOWED,
      ENTITY_REPLACEMENT_NOT_ALLOWED,
      ENTITY_UPDATE_NOT_ALLOWED,
      ENTITY_DELETE_NOT_ALLOWED,
      COLLECTION_BROWSING_NOT_ALLOWED,
      INVALID_ACCOUNT,
      BAD_REQUEST]
  description: string
  messages:
    type: array
    items: Message