#%RAML 1.0 DataType
#
# Usage : to be included in the types section as Task: !include ...

type: object
properties:
  id: string
  job-id: string
  status:
    type: object
    properties:
      run:
        enum: [PENDING, RUNNING, DONE]
      exit:
        enum: [SUCCESS, FAILURE]
  created-at: datetime-only
  started-at: datetime-only
  finished-at: datetime-only
  params: object
  results: object
  callback-url: string